name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/pg-mech-web-app

          # Pull the latest changes
          git pull origin main

          # Build the Docker image with build args
          sudo docker build -t pg-mech-web-app:latest .

          # Stop and remove any existing container
          sudo docker stop pg-mech-web-app || true
          sudo docker rm pg-mech-web-app || true

          # Run the new container
          sudo docker run -d --network=pg-mech-network --name pg-mech-web-app --env-file .env -p 8081:8081 pg-mech-web-app:latest

